export const ADD_FAVORITES = "ADD_FAVORITES"
export const DELETE_FAVORITES = "DELETE_FAVORITES"
export const FILTER_CHARACTERS = "FILTER_CHARACTERS"
export const ORDER_CHARACTERS = "ORDER_CHARACTERS"

